[package]
name = "pdbview"
version = "0.1.0"
authors = ["Lander Brandt <landerbrandt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdb = "0.6"
structopt = "0.3"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
simplelog = "0.8"
serde = { version = "1.0", features = ['derive', 'rc'] }
cpp_demangle = "0.3.1"

[patch.crates-io]
pdb = {path = "../pdb"}