[package]
name = "pdbview"
version = "0.1.0"
authors = ["Lander Brandt <landerbrandt@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ezpdb"
path = "src/lib.rs"

[[bin]]
name = "pdbview"
path = "src/bin.rs"

[dependencies]
pdb = "0.7"
structopt = "0.3"
thiserror = "1.0"
anyhow = "1.0"
log = "0.4"
simplelog = "0.8"
serde = { version = "1.0", features = ['derive', 'rc'] }
serde_json = "1.0"
